export default {
    HIERARCHY: "HIERARCHY",
    COMPONENT: "INSPECTOR",
    FILES: "CONTENT_BROWSER",
    BLUEPRINT: "SHADER_EDITOR",

    UI: "UI",
    PREFERENCES: "PREFERENCES",
    METRICS: "METRICS",
}
