export default {
    UPDATING_SKYLIGHT: "Updating skylight",
    ACTIVE_SKYLIGHT: "Active skylight",
    OUTLINE: "Outline",

    SETTINGS: "Settings",
    VELOCITY_DEF: "Per-object velocity",
    SHADING_VELOCITY: "Velocity",
    GRID: "Grid",
    CREATING_ENTITY: "Creating entity",
    UPDATING_SETTINGS: "Updating settings",
    SPECULAR_LIGHT: "Specular light",
    RESET: "Reset",
    ORIGINAL: "Original",
    SHADER_EDITOR: "Shader editor",
    CAMERA_GIZMO: "Camera gizmo",
    UNDO: "Undo",
    SPOTLIGHT: "Spotlight",
    APPLY: "Apply",
    SSS: "Screen-space shadows",
    EDITOR_POST_PROCESSING: "Editor post-processing",
    POST_PROCESSING: "Post processing",
    MAX_DISTANCE: "Max distance",
    DEPTH_THICKNESS: "Depth thickness",
    HAS_SSS: "Has screen-space shadows",
    VIEWPORT: "Viewport",
    MIN_RAY_STEP: "Minimum ray step",
    SOME_ERROR_OCCURRED: "Some error occurred",
    DEPTH_DELTA: "Depth min delta",
    TOGGLE_TRANSFORMATION_TYPE: "Toggle transformation type",
    HIDE_BUFFERS: "Hide buffers",
    SHOW_BUFFERS: "Show buffers",
    UI_ALREADY_OPEN: "UI already open on other view",
    SIDE_BAR: "Viewport side-bar",
    DEBUG_SHADING: "Debug shading",
    NATURAL_SHADING: "Natural shading",
    LIGHT_ONLY: "Light only",
    SKYLIGHT_INDIRECT: "Skylight indirect",
    MOTION_BLUR: "Motion blur",
    OVERLAY: "Overlay",
    NEW_TAB: "New tab",
    GIZMOS: "Gizmos",
    INDIRECT_LIGHT: "Indirect light",
    SHADING_DYNAMIC_AO: "SSAO",
    SPAWN_ON_ORIGIN: "Spawn on origin",
    SHORTCUTS: "Shortcuts",
    DEPTH_SAMPLER: "Depth sampler",
    AO_SRC: "Unfiltered SSAO",
    SSGI_NORMALS: "Stochastic normals",
    SKYLIGHT: "Skylight",
    BLUR_BLOOM: "Blur color filter",
    GI: "Global illumination",
    DIRECTIONAL_SHADOWS: "Directional shadows",
    ERROR_DURING_COMPILATION: "Error during compilation",
    NEW_FOLDER: "New folder",
    UNKNOWN: "Unknown buffer",
    CUTOFF_SMOOTHING: "Cutoff smoothing",
    OVERDRAW: "Overdraw",
    CUTOFF_DISTANCE: "Cutoff distance",
    CUTOFF: "Cutoff",
    SHOW_OVERLAY: "Show overlay",
    NO_SKYLIGHT_COMPONENT_FOUND: "No Skylight component found on entity",
    RECORDING_SAMPLES: "Recording samples",
    EDITOR_COLOR_CORRECTION: "Editor color correction",
    FILE_ALREADY_OPEN: "File already open",
    GRID_VISIBILITY: "Show grid",
    ICON_VISIBILITY: "Show icons",
    RECOMPUTE_CAPTURE: "Recompute capture",
    MATERIALS: "Materials",
    MATERIALS_TO_DRAW: "Materials to draw",
    CULL_FACE: "Cull face",
    NO_MATERIAL_SELECTED: "No material selected",
    CAMERA_ANIMATION: "Camera smoothing",
    SAVING: "Saving project",
    NO_DEPTH_TEST: "No depth test",
    MOTION_BLUR_SCALE: "Motion blur scale",
    SAVE: "Save",
    SHADING_RANDOM: "Random color",
    SHADING_RANDOM_DEF: "Random color based on instance index",
    CENTER_POINT: "Center point",
    MATERIAL_VALUES: "Material values",
    OVERRIDE_PROPERTIES: "Override properties",
    DYNAMIC: "Dynamic",
    RELATIONS: "Relations",
    ASPECT_RATIO: "Aspect Ratio",
    VIGNETTE: "Vignette effect",
    BLUR_SAMPLES: "Blur samples",
    COPY_ID: "Copy ID",
    ACTIVITY_HISTORY: "Activity history",
    UNDOING_CHANGES: "Undoing changes",
    REDOING_CHANGES: "Redoing changes",
    TOGGLE_RECORD: "Toggle record",
    REDO :"Redo",
    VISIBILITY: "Visibility",
    CHANGED: "Changed",
    RESOLUTION_SCALE: "Resolution scale",
    CLICK_THE_RECORD_BUTTON_TO_RECORD: "Click the record button to start a new recording",
    REFRESH_SCRIPTS_AND_PROBES: "Reloads scripts and UI components and rebuild light probes",
    DONE: "Done",
    EULER: "Euler",
    TRANSFORMING_GROUP: "Transforming group",
    QUATERNION:"Quaternion",
    TAB: "New Tab",
    NO_CUSTOM_COMPONENTS_LINKED: "No custom components linked",
    COPIED: "Copied",
    FOCUS_ON_THIS_VIEW: "Focus on this view",
    FOCUS_ON_CAMERA: "Focus on Camera",
    OPEN_CONSOLE: "Open console",
    NEW_CONSOLE_MESSAGE: "New console message",
    CLEAR: "Clear",
    TOGGLE_NOTIFICATIONS: "Toggle notifications",
    EMPTY: "Empty",
    NOTIFICATIONS: "Notifications",
    SHOW_PREFERENCES: "Show preferences",
    LEVEL: "Level",
    PLAY: "Play",
    REFRESH_STRUCTURE: "Refresh structure",
    PARENT: "Parent",

    UPDATING_STRUCTURE: "Updating structure",

    DEFAULT_LEVEL: "Default",
    NATIVE_MESHES: "Some meshes are embedded with editor/engine",
    NATIVE_MATERIALS: "Some materials are embedded with editor/engine",
    NATIVE_TEXTURES: "Some textures are embedded with editor/engine",

    LOOP_FRAME_TIME: "Loop",
    EXECUTION_FRAME_RATE: "Frame-rate",
    EXECUTION_FRAME_TIME: "Frame-time",
    MEMORY: "Total memory",
    SIMULATION: "Simulation",
    SCRIPTS: "Scripts",

    TOGGLE_FRAMERATE: "Toggle detailed metrics",

    ACTIVE_SHORTCUTS: "Hotkeys: Active view",
    VERSION: "2.0.0-beta",
    LOGGING_ENABLED: "Error logging",
    SHOW_ERROR_LOGS: "Show error logs",


    ERROR_LOADING: "Error loading data.",

    ENTITY: "Entity",
    TRANSLATION: "Translation",
    ROTATION: "Rotation",
    SUB_DIVISION: "Subdivision",
    BRIGHTNESS: "Brightness",
    ALT_FOR_FIXED: "Fixed scaling",
    CTRL_FOR_UNITARY: "Unitary",
    ALT_FOR_PIVOT: "Pivot point",
    FOCUS: "Focus on active entity",

    METRICS: "Metrics",
    STOP: "Stop",

    SENSITIVITY: "Sensitivity",
    IMPORT: "Import",
    SCALE: "Scale",
    FOLIAGE_DISPLACEMENT: "Foliage displacement",
    DENSITY: "Density",
    TOTAL_QUANTITY: "Quantity",


    FOLIAGE_TOOL: "Foliage tool",
    SCULPT_TOOL: "Sculpt tool",
    LOWER: "Lower",
    RAISE: "Raise",
    STROKE: "Brush stroke",
    WIDTH: "Width",
    STRENGTH: "Strength",

    SCULPT: "Sculpt",
    PAINT_LAYERS: "Paint Layers",
    PAINT_FOLIAGE: "Paint Foliage",
    TERRAIN_EDITOR: "Terrain editor",
    SHADING_UV: "Texture coordinates",
    UV_DEF: "UV mapping",
    SHADING_ID: "Entity ID",
    ID_DEF: "Numeric entity identification",
    HEIGHT_MAP_DEF: "Y axis values",
    SHADING_STOCHASTIC: "Stochastic normals",
    STOCHASTIC_DEF: "SSGI normals",
    SHADING_SSGI: "Global illumination",
    SHADING_SSR: "Reflections",
    SSGI_DEF: "Screen-space global illumination",
    SSGI_UNFILTERED_DEF: "Unfiltered global illumination",
    POSITION: "Position",
    POSITION_DEF: "Fragment position",

    SHADING_METALLIC: "Metallic",
    METALLIC_DEF: "Material metallic",

    SHADING_ROUGHNESS: "Roughness",
    ROUGHNESS_DEF: "Material roughness",

    SHADING_AMBIENT: "Ambient",
    AMBIENT_DEF: "Ambient color (Probes)",

    G_AO_DEF: "Material AO",
    G_BUFFER: "G-Buffer",
    SCENE: "Scene",
    RECONSTRUCTED_NORMALS: "Screen",
    DETAIL_DEF: "PBR shading",
    LIGHT_DEF: "Light details",
    UNLIT_DEF: "Material albedo",
    AO_DEF: "Scene AO",
    DEPTH_DEF: "Linear depth",
    NORMAL_DEF: "Mesh normals",

    PICKER: "Element picker",
    SELECT_ALL: "Select all",
    ADD_ELEMENT: "Add element",
    CAMERA_POSITION: "Camera position",
    SELECT: "Select",
    ALL: "All",
    NONE: "None",
    INVERT: "Invert",
    TRANSFORMATION_ORIENTATION: "Transformation orientation",
    LOCAL: "Local",
    GLOBAL: "Global",

    MOVEMENT_SPEED: "Movement speed",

    SPRITE: "Sprite",
    SPRITE_RENDERER: "New sprite renderer",
    MESH_RENDERER: "New mesh renderer",

    MESHES: "Meshes",
    DRAG_DROP: "Drop meshes or scenes",
    EDITOR: "Scene Editor",
    UI: "UI Editor",
    EMPTY_ENTITY: "Empty Entity",
    LAYOUT: "Layout",
    ADD_DETAILS: "Add entity",
    ACTIVE_ENTITY: "Active Entity",
    ACTIVE: "Active",
    DELETE_VIEW: "Delete view",

    UTILS: "Utils",
    AMBIENT: "Ambient",
    TOP: "Top",
    LEFT: "Left",
    RIGHT: "Right",
    BOTTOM: "Bottom",
    FRONT: "Front",
    BACK: "Back",
    SWITCH_PROJECTION: "Switch between last Orthographic/Perspective",
    MOVE_IN_SCREEN_SPACE: "Move camera in screen-space",
    DOUBLE_CLICK: "- Double click to center",

    ICONS: "Icons",
    FPS: "Frames per second",
    SMOOTHING: "Smoothing",
    ICON_SIZE: "icon size",
    SHADING_LIGHT: "Light only",
    SHADING_UNLIT: "Albedo",
    SHADING_NORMAL: "Normals",
    SHADING_DEPTH: "Depth",
    SHADING_AO: "Ambient occlusion",
    SHADING_DETAIL: "Details",

    ZOOM: "Zoom",

    MOVEMENT_GRID: "Movement grid",
    TRANSLATION_GRID: "Translation",
    SCALE_GRID: "Scale",
    ROTATION_GRID: "Rotation (degrees)",
    SELECTION: "Selection",
    T_GIZMO: "Translation",
    R_GIZMO: "Rotation",
    S_GIZMO: "Scale",
    BACKGROUND: "Background",

    SHOW_MAIN_ENTITY: "Show selected",
    REMOVE_FILTER: "Remove filter",
    DEACTIVATE: "Activate/Deactivate entity",
    SELECTED_CHILD: "Child entity is selected",
    FOCUS_LOCKED_ENTITY: "Focus on locked entity",
    TRANSFORM: "Transformation",

    PROBE: "Probe",

    COMPONENT_FILTER: "Filter by component",
    HIERARCHY_SOURCE: "Change hierarchy view",
    ENGINE: "Engine",
    FOLDER: "New Folder",
    OBJECT: "Object",
    SPAWNING: "Spawning",
    CLICK_TO_SHOW_OBJECT: "Click to show object",
    VIEW: "View",
    TOGGLE_CLEAR_ON_PLAY: "Clear on play",

    ERRORS: "Show errors",
    WARNINGS: "Show warnings",
    LOGS: "Show logs",

    ADD: "Add",
    COMPILE: "Compile",

    TOGGLE_GRID: "Toggle grid",
    INFORMATION: "Information",
    NEEDS_COMPILATION: "Please compile the shader.",

    NO_ERRORS: "No errors were found.",
    NODE: "Node",
    STATUS: "Status",
    SOURCE: "Source code",
    COMPILING: "Compiling shaders",
    NOT_APPLIED: "Material doesn't seem to be applied to a mesh.",
    SAVED: "Saved",
    ERROR: "Some error occurred",

    METADATA: "Metadata",
    DISTANCE: "Distance",
    DISTANCE_SQUARED: "Dist. squared",
    SHADOW_VIEW_PLANES: "Shadow map view planes",
    BIAS: "Bias",
    PCF_SAMPLES: "Filtering samples",
    SAMPLER: "Sampler",
    SAMPLER_SCALE: "RGB multiplier",
    UV_SCALE: "UV scale",

    LOCKED: "Is locked",
    HAS_COLLISION: "Has collision",

    LAYERS_CONTROLLER: "Layer controller",
    REMOVE_LAYER: "Remove layer",
    LAYER: "Layer",
    LAYERS: "Layers",
    PARALLAX_OCCLUSION_MAPPING: "Parallax occlusion mapping",
    DISCARD_OFF_PIXELS: "Discard off pixels",
    ADD_LAYER: "Add layer",
    TERRAIN_COMPONENT: "Terrain component",

    BRUSH_SETTINGS: "Brush settings",
    OPACITY: "Opacity",

    EDIT_HEIGHT_MAP: "Edit height map",
    IMPORT_IMAGE: "Import image",
    DIMENSIONS: "Dimensions",
    HEIGHT_SCALE: "Height scale",
    DIMENSION_MULTIPLIER: "Size multiplier",

    DEPTH_THRESHOLD: "Depth threshold",
    BINARY_SEARCH: "Binary search iterations",
    POWER: "Power",

    USE_SAMPLER: "Use texture",
    SCALE_ALBEDO: "Albedo scale",
    FALLBACK_VALUE: "Fallback value",

    NOISE_SCALE: "Noise scale",
    ALBEDO: "Albedo",
    NORMAL: "Normal",
    METALLIC: "Metallic",
    EMISSION: "Emission",
    ROUGHNESS: "Roughness",

    NO_UNIFORMS: "No dynamic inputs found",
    INERTIA: "Inertia",
    IMPORT_LAYOUT: "Import UI layout",
    CODE_PREVIEW: "Code preview",
    ANCHOR_ELEMENT_ID: "Anchor element",
    ELEMENT_ID: "Element ID",
    UI_COMPONENT: "UI component",
    UI_WRAPPER: "Content wrapper",
    WRAP_CONTENT: "Wrap content",
    WRAPPER_ID: "Wrapper ID",
    WRAPPER_STYLES: "Wrapper styles",
    VALUE: "Value",
    KEY: "Key",

    MASS: "Mass",
    COLLISION_TYPE: "Collision type",
    CENTER: "Center",
    HEIGHT: "Height",
    DIRECTION: "Direction",
    PHYSICS_COLLIDER: "Physics collider",
    RIGID_BODY: "Rigid body",

    SHOW_ON_CB: "Show on content browser",
    ALLOCATING_MESH: "Allocating mesh",
    REGENERATE_NORMALS_AND_TANGENTS: "Regenerate normal and tangents",
    RENDERING: "Rendering",
    CONTRIBUTION: "Contribution",
    CONTRIBUTE_TO_PROBES: "Contribute to probes",
    INDIRECT_LIGHTS: "Indirect lighting",
    DIFFUSE_PROBE_INFLUENCE: "Diffuse probe influence",
    SPECULAR_PROBE_INFLUENCE: "Specular probe influence",
    PIVOT_POINT: "Pivot point",

    PRIMITIVES: "Primitives",
    CONTENT_BROWSER: "Content browser",
    COLOR: "Color",
    MATERIAL_UPDATED: "Material updated",
    CREATION_DATE: "Creation date",
    CHILDREN: "Children",
    FILE_SIZE: "Size (MB)",
    FILE_EXTENSION: "Extension",
    ASSETS_PATH: "Path",
    MORE_INFO: "More info",

    LOADING_MATERIAL: "Loading material",
    ADD_DRAG_DROP: "Add component, mesh, texture or material",
    OPENGL_DOCS: "Learn more",
    TEXTURE_FILTERING: "Texture filtering function",
    TEXTURE_MIN_FILTER: "Minifying",
    TEXTURE_MAG_FILTER: "Magnification",

    NEAREST_MIPMAP_LINEAR: "Nearest mip-map linear",
    LINEAR_MIPMAP_NEAREST: "Linear mip-map nearest",
    LINEAR_MIPMAP_LINEAR: "Linear mip-map linear",
    NEAREST_MIPMAP_NEAREST: "Nearest mip-map nearest",

    NEAREST: "Nearest",
    LINEAR: "Linear",
    TEXTURE_WRAPPING: "Wrapping",
    wrapT: "Vertical",
    wrapS: "Horizontal",
    MIRRORED_REPEAT: "Mirrored repeat",
    REPEAT: "Repeat",
    CLAMP_TO_EDGE: "Clamp to edge",
    CLAMP_TO_BORDER: "Clamp to border",


    ALLOCATING_TEXTURE: "Allocating texture",
    UPDATING_ASSET: "Updating asset",
    FLIP_Y: "Y",
    FLIP_X: "X",
    FLIP_TEXTURE: "Flip texture",
    TEXTURE_FORMAT: "Texture format",
    FROM_LAYOUT: "Load from UI Layout",
    FOCUSED_ON_ENGINE: "Priority on: Entity",
    FOCUSED_ON_UI: "Priority on: UI element",

    EDITING_ELEMENT: "Editing element",
    EDITING_ENTITY: "Editing entity",
    COULD_NOT_FIND: "Could not find component for item",
    MATERIAL_LOADED: "Material loaded successfully",
    ERROR_LOADING_FILE: "Error loading file.",
    SPECULAR_PROBE: "Specular probe",
    MULTIPLIER: "Multiplier",
    INTENSITY: "Intensity",
    INTENSITY_COLOR: "Intensity & color",
    DISTORTION: "Distortion",
    THRESHOLD: "Threshold",
    BLOOM: "Bloom",
    COLOR_CORRECTION: "Color correction",
    GAMMA: "Gamma",
    EXPOSURE: "Exposure",
    FILM_GRAIN: "Film grain",
    CHROMATIC_ABERRATION: "Chromatic aberration",

    ENABLED: "Enabled",
    ORTHO_PROJECTION: "Orthographic projection",
    PROJECTION_SIZE: "Orthographic size",
    FOV: "Field Of View",
    VIEW_PLANES: "View Planes",
    FAR: "Far",
    NEAR: "Near",
    MY_ENTITY: "My entity",
    NAME: "Name",
    STOP_SIMULATION: "Stop the simulation to change attributes.",

    SCALING_LOCAL: "Scaling (local)",
    RECOMPUTE_PROBES: "Probe re-computation needed",
    RESOLUTION: "Resolution",
    FXAA: "FXAA",
    PHYSICS: "Physics",
    ANTI_ALIASING: "Anti-aliasing",

    PHYSICS_SUB_STEPS: "Simulation sub-steps",
    PHYSICS_SIMULATION_STEP: "Simulation step interval",

    SSR: "Screen space reflections",
    AO: "Ambient occlusion",
    STEP_SIZE: "Step size",
    STEPS: "Steps",
    SSGI: "Global illumination",
    SHADOWS: "Shadows",
    LIGHTS: "Lights",
    SMOOTHING_SAMPLES: "Smoothing samples",
    SAMPLES: "Samples",
    RADIUS: "Radius",
    FALLOFF: "Falloff",
    AREA: "Area",
    BASE: "Base",
    ATTENUATION: "Attenuation",
    CASTS_SHADOWS: "Casts shadows",
    ADD_COMPONENT: "Add component",
    QUERY_KEY: "Query key",
    REMOVE_COMPONENT: "Remove component",
    CAMERA: "Camera",
    DIRECTIONAL_LIGHT: "Directional light",
    MESH: "Mesh",
    POINT_LIGHT: "Point Light",
    TRANSFORMATION: "Transformation",

    KEEP_SAME_SIZE: "Lock viewport size",
    INSTANCED_RENDERING: "Instanced rendering",
    QUAD_SIZE: "Viewport size",
    ALWAYS_FACE_CAMERA: "Always face camera",

    PRIMITIVE: "Primitive",
    UI_LAYOUT: "UI layouts",
    COMPONENT: "Component",


    TEXTURE: "Texture",
    COLLECTION: "Collection",

    SIZE: "Size",
    CREATION: "Creation date",


    ROW_VIEW: "Rows",
    CARD_VIEW: "Cards",


    DELETING_ITEMS: "Deleting items",

    FILE_TYPE: "File type",
    ITEM_NAME: "Name",
    ITEM_TYPE: "Type",
    REGISTRY_ID: "Registry",

    SUCCESSFUL_DELETE: "Items deleted",
    CREATE: "Create",
    OPENING_LEVEL: "Opening level",
    OPENING_FILE: "Opening file",


    SELECT_NONE: "Select none",
    SELECT_INVERT: "Invert selection",
    DELETE: "Delete",

    CUT: "Cut",
    PASTE: "Paste",
    RENAME: "Rename",
    OPEN_WITH_EXPLORER: "Open with explorer",
    FORWARD: "Forward",
    REFRESH: "Refresh",
    REFRESHING: "Refreshing content-browser",
    GO_TO_PARENT: "Go to parent",

    JAVASCRIPT_PACKAGE: "Javascript package",
    JSON_OBJECT: "JSON object",

    ASSETS: "Assets",

    OPTIONS: "Options",
    BACK_DIR: "Action: Go back",
    FORWARD_DIR: "Action: Go forward",
    PARENT_DIR: "Action: Go to parent",
    CREATE_FOLDER: "Create folder",
    FILTER_TYPE: "Filter by file type",


    ABOUT: "About",
    EXIT: "Exit",
    PROJECTION_ENGINE: "Projection Engine",
    FOOTER: "This program comes with absolutely no warranty.",
    MIT: "Under GPL Version 3 license.",
    COPYRIGHT: "Copyright (c) 2022 Projection Engine",

    CODE: "Code",
    MATERIAL: "Material",

    CUBE: "Cube (Embedded)",
    SPHERE: "Sphere (Embedded)",
    PLANE: "Plane (Embedded)",
    CYLINDER: "Cylinder (Embedded)",

    NOTHING: "Nothing found",
    DEFAULT_MATERIAL: "Default material (Embedded)",
    REMOVE_SCRIPT: "Remove script",
    SEARCH: "Search",

    HUE: "Hue",
    SATURATION: "Saturation",

    PREFERENCES: "Preferences",
    SPLIT_TOP: "Split top",
    SPLIT_BOTTOM: "Split bottom",
    SPLIT_RIGHT: "Split right",
    SPLIT_LEFT: "Split left",
    CLOSE_VIEW: "Close view",
    MISC: "Misc",
    DATA: "Data",
    CODE_EDITOR: "Code editor",
    CLOSE: "Close",
    HIERARCHY: "Hierarchy",
    INSPECTOR: "Inspector",
    CONSOLE: "Console",
    IMAGE: "Texture",
    TERRAIN: "terrain",


}