enum Routes {
  ENTITIES = "ENTITIES",
  LOAD_LEVEL = "LOAD_LEVEL",
  LOAD_PROJECT_METADATA = "LOAD_PROJECT_METADATA",
  REFRESH_CONTENT_BROWSER = "refresh-content-browser",
  FILE_DIALOG = "FILE_DIALOG",
  READ_FILE = "READ_FILE",
  REGISTER_CONTEXT_MENU = "REGISTER_CONTEXT_MENU",
  OPEN_CONTEXT_MENU = "OPEN_CONTEXT_MENU",
  DESTROY_CONTEXT_MENU = "DESTROY_CONTEXT_MENU",
  SET_PROJECT_CONTEXT= "SET_PROJECT_CONTEXT",
  READ_REGISTRY = "READ_REGISTRY",
  CREATE_REG = "CREATE_REG",
  RESOLVE_NAME = "RESOLVE_NAME",
  UPDATE_REG = "UPDATE_REG",
  CLOSE_EDITOR = "CLOSE_EDITOR",
  EDITOR_INITIALIZATION = "EDITOR_INITIALIZATION",
  OPEN_SELECTION = "OPEN_SELECTION"
}

export default Routes
