export default class Localization {


    static SETTINGS = {
        MAIN: {
            RESET: "Reset",
            ORIGINAL: "Original",
            SHADER_EDITOR: "Shader editor",
            CONTENT_BROWSER: "Content browser",
            UNDO: "Undo changes",
            BACKGROUND: "Background",
            PREFERENCES: "Preferences",
            APPLY: "Apply",
            POST_PROCESSING: "Post processing",
            RENDERING: "Rendering",
            VIEWPORT: "Viewport",
            ENABLED: "Enabled",
            COLOR: "Color",

            EDITOR: "Editor",
            SIDE_BAR: "Viewport side-bar",

            SHORTCUTS: "Shortcuts",
            GRID_VISIBILITY: "Show grid",
            ICON_VISIBILITY: "Show icons",
            CAMERA_ANIMATION: "Camera smoothing",
            ICON_SIZE: "Icons size"
        }
    }
    static PROJECT = {
        SAVING: "Saving project",
        CODE_EDITOR: {
            SAVE: "Save",
            TITLE: "Code editor",
        },
        CONTROL: {
            SHOW_PREFERENCES: "Show preferences",
            OPTIONS: "Options",
            LEVEL: "Level",
            PLAY: "Play",
            STOP: "Stop",
            BUILD_PROBES: "Build probes",
            BUILDING_PROBES: "Building probes",

            SAVE: "Save",
            DEFAULT_LEVEL: "Default",
        },
        INFO: {
            LOOP_FRAME_TIME: "Loop",
            EXECUTION_FRAME_RATE: "Frame-rate",
            EXECUTION_FRAME_TIME: "Frame-time",
            MEMORY: "Total memory",
            RENDERING: "Rendering",
            SIMULATION: "Simulation",
            SCRIPTING: "Scripts",

            TOGGLE_FRAMERATE: "Toggle detailed metrics",
            NEW_MESSAGE: "New console message",
            ACTIVE_SHORTCUTS: "Hotkeys: Active view",
            VERSION: "1.0.0-beta",
            LOGGING_ENABLED: "Error logging",
            SHOW_ERROR_LOGS: "Show error logs",
        },
        ALERTS: {
            UNDO_SETTINGS: "Undo: preferences.",
            REDO_SETTINGS: "Redo: preferences.",
            UNDO_ENTITIES: "Undo: entity.",
            REDO_ENTITIES: "Redo: entity.",
            ERROR_LOADING: "Error loading data.",
        },
        VIEWPORT: {
            PREFERENCES: "Preferences",
            FOCUS: "Focus on active entity",
            PHYSICS_COLLIDER: "Physics collider",
            PIVOT: "Pivot point",
            METRICS: "Metrics",
            SWITCH_BETWEEN_CAMERAS: "Switch between cameras",
            LEVEL: "Level",
            STOP: "Stop",
            BUILD_PROBES: "Build probes",
            BUILDING_PROBES: "Building probes",

            SAVE: "Save",
            DEFAULT_LEVEL: "Default",
            SENSITIVITY: "Sensitivity",
            IMPORT: "Import",
            SCALE: "Scale",
            FOLIAGE_DISPLACEMENT: "Foliage displacement",
            DENSITY: "Density",
            TOTAL_QUANTITY: "Quantity",


            FOLIAGE_TOOL: "Foliage tool",
            SCULPT_TOOL: "Sculpt tool",
            LOWER: "Lower",
            RAISE: "Raise",
            STROKE: "Brush stroke",
            WIDTH: "Width",
            STRENGTH: "Strength",

            SCULPT: "Sculpt",
            PAINT_LAYERS: "Paint Layers",
            PAINT_FOLIAGE: "Paint Foliage",
            TERRAIN: "Terrain editor",
            SHADING_UV: "Texture coordinates",
            UV_DEF: "UV mapping",
            SHADING_ID: "Entity ID",
            ID_DEF: "Numeric entity identification",
            HEIGHT_MAP_DEF: "Y axis values",
            SHADING_STOCHASTIC: "Stochastic normals",
            STOCHASTIC_DEF: "SSGI normals",
            SHADING_SSGI: "Global illumination",
            SSGI_DEF: "SSGI",
            SHADING_POSITION: "Position",
            POSITION_DEF: "Fragment position",

            SHADING_METALLIC: "Metallic",
            METALLIC_DEF: "Material metallic",

            SHADING_ROUGHNESS: "Roughness",
            ROUGHNESS_DEF: "Material roughness",

            SHADING_AMBIENT: "Ambient",
            AMBIENT_DEF: "Ambient color (Probes)",

            G_AO_DEF: "Material AO",
            G_BUFFER: "G-Buffer",
            SCENE: "Scene",
            RECONSTRUCTED_NORMALS: "Reconstructed normals",
            RECONSTRUCTED_NORMALS_DEF: "Depth reconstruction",
            DETAIL_DEF: "PBR shading",
            LIGHT_DEF: "Light details",
            UNLIT_DEF: "Material albedo",
            AO_DEF: "Scene AO",
            DEPTH_DEF: "Linear depth",
            NORMAL_DEF: "Mesh normals",

            PICKER: "Element picker",
            SELECT_ALL: "Select all",
            ADD_ELEMENT: "Add element",
            CAMERA_POSITION: "Camera position",
            SELECT: "Select",
            ALL: "All",
            NONE: "None",
            INVERT: "Invert",
            TRANSFORMATION_ORIENTATION: "Transformation orientation",
            LOCAL: "Local",
            GLOBAL: "Global",

            CAMERA_BEHAVIOUR: "Interaction",
            TURN_SPEED: "Turn speed",
            MOVEMENT_SPEED: "Movement speed",
            SCROLL_SPEED: "Scroll speed",

            VIEW: "View",
            SPRITE: "Sprite",
            SPRITE_RENDERER: "New sprite renderer",
            MESH_RENDERER: "New mesh renderer",
            CYLINDER: "Cylinder",
            CUBE: "Cube",
            PLANE: "Plane",
            SPHERE: "Sphere",

            MESHES: "Meshes",
            DRAG_DROP: "Drop meshes or scenes",
            PLAY: "Play",
            EDITOR: "Scene Editor",
            UI: "UI Editor",
            EMPTY_ENTITY: "Empty Entity",
            LAYOUT: "Layout",
            ADD: "Add",
            ADD_DETAILS: "Add entity",
            CAMERA: "Camera",
            TITLE: "Viewport",
            ACTIVE_ENTITY: "Active Entity",
            DELETE_VIEW: "Delete view",
            NEW_TAB: "New Tab",
            POINT_LIGHT: "Point Light",
            DIRECTIONAL_LIGHT: "Directional Light",
            SPOT_LIGHT: "SpotLight",
            SPECULAR_PROBE: "Specular Probe",
            DIFFUSE_PROBE: "Diffuse Probe",
            UTILS: "Utils",
            AMBIENT: "Ambient",
            LIGHTS: "Lights",
            TOP: "Top",
            LEFT: "Left",
            RIGHT: "Right",
            BOTTOM: "Bottom",
            FRONT: "Front",
            BACK: "Back",
            SWITCH_PROJECTION: "Switch between last Orthographic/Perspective",
            MOVE_IN_SCREEN_SPACE: "Move camera in screen-space",
            DOUBLE_CLICK: "- Double click to center",

            GRID: "Grid",
            ICONS: "Icons",
            FPS: "Frames per second",
            SMOOTHING: "Smoothing",
            ICON_SIZE: "icon size",
            SHADING_LIGHT: "Light only",
            SHADING_UNLIT: "Unlit",
            SHADING_NORMAL: "Normals",
            SHADING_DEPTH: "Depth",
            SHADING_AO: "Ambient Occlusion",
            SHADING_DETAIL: "Details",
            SHADING_SWITCH: "Switching to details shading model",
            FAR: "Far plane",
            NEAR: "Near plane",
            FOV: "Field Of View",
            ZOOM: "Zoom",

            MOVEMENT_GRID: "Movement grid",
            TRANSLATION_GRID: "Translation",
            SCALE_GRID: "Scale",
            ROTATION_GRID: "Rotation (degrees)",
            SELECTION: "Selection",
            T_GIZMO: "Translation",
            R_GIZMO: "Rotation",
            S_GIZMO: "Scale",
            BACKGROUND: "Background",

        },
        HIERARCHY: {
            REMOVE_FILTER: "Remove filter",
            DEACTIVATE: "Activate/Deactivate entity",
            SELECTED_CHILD: "Child entity is selected",
            FOCUS_LOCKED_ENTITY: "Focus on locked entity",
            TRANSFORM: "Transformation",
            DIRECTIONAL_LIGHT: "Directional Light",
            POINT_LIGHT: "Point Light",
            MESH: "Mesh",
            CAMERA: "Camera",
            PROBE: "Probe",

            COMPONENT_FILTER: "Filter by component",
            HIERARCHY_SOURCE: "Change hierarchy view",
            ENGINE: "Engine",
            UI: "UI",
            TITLE: "Hierarchy",
            NEW_FOLDER: "New Folder",
            SEARCH: "Search",

            KEY: "Key",
            VALUE: "Value"
        },
        CONSOLE: {
            CLICK_TO_SHOW_OBJECT: "Click to show object",
            VIEW: "View",
            TOGGLE_CLEAR_ON_PLAY: "Clear on play",
            TITLE: "Console",
            CLEAR: "Clear",
            ERRORS: "Show errors",
            WARNINGS: "Show warnings",
            LOGS: "Show logs"
        },
        SHADER_EDITOR: {
            ADD: "Add",
            COLOR: "Color",
            TITLE: "Shader Editor",
            SAVE: "Save",
            COMPILE: "Compile",
            SELECT: "Select",
            ALL: "All",
            NONE: "None",
            INVERT: "Invert",
            GRID: "Toggle movement grid",
            NAME: "Name",
            INFORMATION: "Information",
            NEEDS_COMPILATION: "Please compile the shader.",
            ERRORS: "Errors",
            NO_ERRORS: "No errors were found.",
            NODE: "Node",
            STATUS: "Status",
            SOURCE: "Source code",
            COMPILING: "Compiling shaders",
            NOT_APPLIED: "Material doesn't seem to be applied to a mesh.",
            SAVED: "Saved",
            ERROR: "Some error occurred"
        },
        INSPECTOR: {
            LOCKED: "Is locked",
            HAS_COLLISION: "Has collision",

            LAYERS_CONTROLLER: "Layer controller",
            REMOVE_LAYER: "Remove layer",
            LAYER: "Layer",
            SCALE: "Scale",
            ADD_LAYER: "Add layer",
            TERRAIN_COMPONENT: "Terrain component",
            TERRAIN: "Terrain",

            BRUSH_SETTINGS: "Brush settings",
            OPACITY: "Opacity",

            EDIT_HEIGHT_MAP: "Edit height map",
            IMPORT_IMAGE: "Import image",
            DIMENSIONS: "Dimensions",
            HEIGHT_SCALE: "Height scale",
            DIMENSION_MULTIPLIER: "Size multiplier",

            DEPTH_THRESHOLD: "Depth threshold",
            BINARY_SEARCH: "Binary search iterations",
            POWER: "Power",

            USE_SAMPLER: "Use texture",
            SCALE_ALBEDO: "Albedo scale",
            FALLBACK_VALUE: "Fallback value",

            NOISE_SCALE: "Noise scale",
            ALBEDO: "Albedo",
            NORMAL: "Normal",
            METALLIC: "Metallic",
            EMISSION: "Emission",
            ROUGHNESS: "Roughness",

            NO_UNIFORMS: "No dynamic inputs found",
            INERTIA: "Inertia",
            IMPORT_LAYOUT: "Import UI layout",
            CODE_PREVIEW: "Code preview",
            ANCHOR_ELEMENT_ID: "Anchor element",
            ELEMENT_ID: "Element ID",
            UI_COMPONENT: "UI component",
            UI_WRAPPER: "Content wrapper",
            WRAP_CONTENT: "Wrap content",
            WRAPPER_ID: "Wrapper ID",
            WRAPPER_STYLES: "Wrapper styles",
            VALUE: "Value",
            KEY: "Key",

            MASS: "Mass",
            COLLISION_TYPE: "Collision type",
            CENTER: "Center",
            HEIGHT: "Height",
            DIRECTION: "Direction",
            PHYSICS_COLLIDER: "Physics collider",
            RIGID_BODY: "Rigid body",

            SHOW_ON_CB: "Show on content browser",
            ALLOCATING_MESH: "Allocating mesh",
            REGENERATE_NORMALS_AND_TANGENTS: "Regenerate normal and tangents",
            RENDERING: "Rendering",
            CONTRIBUTION: "Contribution",
            MATERIAL: "Material",
            CONTRIBUTE_TO_PROBES: "Contribute to probes",
            INDIRECT_LIGHTS: "Indirect lighting",
            DIFFUSE_PROBE_INFLUENCE: "Diffuse probe influence",
            SPECULAR_PROBE_INFLUENCE: "Specular probe influence",


            PRIMITIVES: "Primitives",
            CONTENT_BROWSER: "Content browser",
            ENGINE: "Engine entity",
            UI: "UI element",

            COLOR: "Color",
            MATERIAL_UPDATED: "Material updated",
            CREATION_DATE: "Creation date",
            CHILDREN: "Children",
            FILE_SIZE: "Size (MB)",
            FILE_EXTENSION: "Extension",
            REGISTRY_ID: "File ID",
            ASSETS_PATH: "Path",
            MORE_INFO: "More info",

            LOADING_MATERIAL: "Loading material",
            ADD_DRAG_DROP: "Add component, mesh, texture or material",
            OPENGL_DOCS: "Learn more",
            TEXTURE_FILTERING: "Texture filtering function",
            TEXTURE_MIN_FILTER: "Minifying",
            TEXTURE_MAG_FILTER: "Magnification",

            NEAREST_MIPMAP_LINEAR: "Nearest mip-map linear",
            LINEAR_MIPMAP_NEAREST: "Linear mip-map nearest",
            LINEAR_MIPMAP_LINEAR: "Linear mip-map linear",
            NEAREST_MIPMAP_NEAREST: "Nearest mip-map nearest",

            NEAREST: "Nearest",
            LINEAR: "Linear",
            TEXTURE_WRAPPING: "Wrapping",
            wrapT: "Vertical",
            wrapS: "Horizontal",
            MIRRORED_REPEAT: "Mirrored repeat",
            REPEAT: "Repeat",
            CLAMP_TO_EDGE: "Clamp to edge",
            CLAMP_TO_BORDER: "Clamp to border",


            ALLOCATING_TEXTURE: "Allocating texture",
            UPDATING_ASSET: "Updating asset",
            FLIP_Y: "Y",
            FLIP_X: "X",
            FLIP_TEXTURE: "Flip texture",
            TEXTURE_FORMAT: "Texture format",
            FROM_LAYOUT: "Load from UI Layout",
            FOCUSED_ON_ENGINE: "Priority on: Entity",
            FOCUSED_ON_UI: "Priority on: UI element",

            EDITING_ELEMENT: "Editing element",
            EDITING_ENTITY: "Editing entity",
            COULD_NOT_FIND: "Could not find component for item",
            MATERIAL_LOADED: "Material loaded successfully",
            ERROR_LOADING_FILE: "Error loading file.",
            SPECULAR_PROBE: "Specular probe",
            MULTIPLIER: "Multiplier",
            INTENSITY: "Intensity",
            INTENSITY_COLOR: "Intensity & color",
            DISTORTION: "Distortion",
            THRESHOLD: "Threshold",
            BLOOM: "Bloom",
            COLOR_CORRECTION: "Color correction",
            GAMMA: "Gamma",
            EXPOSURE: "Exposure",
            FILM_GRAIN: "Film grain",
            CHROMATIC_ABERRATION: "Chromatic aberration",

            ENABLED: "Enabled",
            POST_PROCESSING: "Editor post-processing",
            TITLE: "Inspector",
            SCRIPTS: "Scripts",
            ORTHO_PROJECTION: "Orthographic projection",
            PROJECTION_SIZE: "Orthographic size",
            FOV: "Field Of View",
            VIEW_PLANES: "View Planes",
            FAR: "Far",
            NEAR: "Near",
            MY_ENTITY: "My entity",
            NAME: "Name",
            STOP_SIMULATION: "Stop the simulation to change attributes.",
            TRANSLATION: "Translation",
            ROTATION: "Rotation",
            SCALING_LOCAL: "Scaling (local)",
            RECOMPUTE_PROBES: "Probe re-computation needed",
            RESOLUTION: "Resolution",
            AA: "FXAA Anti-aliasing",
            SSR: "Screen space reflections",
            AO: "Ambient occlusion",
            STRENGTH: "Strength",
            STEP_SIZE: "Step size",
            STEPS: "Steps",
            SSGI: "Global illumination",
            SHADOWS: "Shadows",
            LIGHTS: "Lights",
            SMOOTHING_SAMPLES: "Smoothing samples",
            SAMPLES: "Samples",
            RADIUS: "Radius",
            FALLOFF: "Falloff",
            AREA: "Area",
            BASE: "Base",
            ATTENUATION: "Attenuation",
            CASTS_SHADOWS: "Casts shadows",
            SIZE: "Size",
            ADD_COMPONENT: "Add component",
            QUERY_KEY: "Query key",
            REMOVE_COMPONENT: "Remove component",
            CAMERA: "Camera",
            DIRECTIONAL_LIGHT: "Directional light",
            MESH: "Mesh",
            POINT_LIGHT: "Point Light",
            PROBE: "Probe",
            TRANSFORMATION: "Transformation",

            SPRITE: "Sprite",
            IMAGE: "Image",
            KEEP_SAME_SIZE: "Lock viewport size",
            INSTANCED_RENDERING: "Instanced rendering",
            QUAD_SIZE: "Viewport size",
            ALWAYS_FACE_CAMERA: "Always face camera"

        },

        FILES: {
            MESH: "Meshes",
            LEVEL: "Levels",
            UI_LAYOUT: "UI layouts",
            COMPONENT: "Components",
            MATERIAL: "Materials",
            MATERIAL_INSTANCE: "Material instances",
            SIMPLE_MATERIAL: "Simple materials",
            TERRAIN_MATERIAL: "Terrain materials",
            TERRAIN: "Terrains",
            TEXTURE: "Textures",
            SCENE: "Scenes",

            NAME: "Name",
            SIZE: "Size",
            CREATION: "Creation date",


            ROW_VIEW: "Rows",
            CARD_VIEW: "Cards",
            NEW_TERRAIN_MATERIAL: "New terrain material",
            NEW_TERRAIN: "New terrain",
            DELETING_ITEMS: "Deleting items",
            NEW_SIMPLE_MATERIAL: "New simple material",
            FILE_TYPE: "File type",
            CHILDREN: "Children quantity",
            ITEM_NAME: "Name",
            ITEM_TYPE: "Type",
            REGISTRY_ID: "Registry",
            NEW_UI_LAYOUT: "New UI Layout",
            NEW_LEVEL: "New Level",
            SUCCESSFUL_DELETE: "Items deleted",
            CREATE: "Create",
            OPENING_LEVEL: "Opening level",
            OPENING_FILE: "Opening file",
            SEARCH: "Search",
            SELECT: "Select",
            TITLE: "Content Browser",
            EMPTY: "Empty folder",
            SELECT_ALL: "Select all",
            SELECT_NONE: "Select none",
            SELECT_INVERT: "Invert selection",
            BACK: "Back",
            DELETE: "Delete",

            CUT: "Cut",
            PASTE: "Paste",
            RENAME: "Rename",
            NEW_FOLDER: "New Folder",
            OPEN_WITH_EXPLORER: "Open with explorer",
            FORWARD: "Forward",
            REFRESH: "Refresh",
            REFRESHING: "Refreshing content-browser",
            GO_TO_PARENT: "Go to parent",

            NEW_COMPONENT: "New Component",
            NEW_MATERIAL: "New Material",
            NEW_MATERIAL_INSTANCE: "New Material Instance",

            ASSETS: "Assets",
            BOOKMARKS: "Bookmarks",
            IMPORT: "Import",
            SIDE_BAR: "Sidebar",
            OPTIONS: "Navigation options",
            VIEW: "View",
            BACK_DIR: "Action: Go back",
            FORWARD_DIR: "Action: Go forward",
            PARENT_DIR: "Action: Go to parent",
            CREATE_FOLDER: "Create folder",
            ADD_BOOKMARK: "Add folder to bookmarks",
            FILTER_TYPE: "Filter by file type"
        }
    }
    static COMPONENTS = {
        RANGE: {
            UNDO: "Default values"
        },
        FRAME: {
            ABOUT: "About",
            EXIT: "Exit",
            TITLE: "Projection Engine",
            VERSION: Localization.PROJECT.INFO.VERSION,
            FOOTER: "This program comes with absolutely no warranty.",
            MIT: "MIT License",
            COPYRIGHT: "Copyright (c) 2022 Projection Engine"
        },
        SELECTOR: {
            TERRAIN: "Terrain",
            CODE: "Code",
            UI: "UI layout",
            IMAGE: "Texture",
            MATERIAL: "Material",
            MESH: "Mesh",

            CUBE: "Cube (Embedded)",
            SPHERE: "Sphere (Embedded)",
            PLANE: "Plane (Embedded)",
            CYLINDER: "Cylinder (Embedded)",

            EMPTY: "Empty",
            NOTHING: "Nothing found",
            DEFAULT_MATERIAL: "Default material (Embedded)",
            REMOVE_SCRIPT: "Remove script",
            SEARCH: "Search"
        },
        COLOR: {
            HUE: "Hue",
            SATURATION: "Saturation",
            VALUE: "Value"
        },
        VIEWS: {
            SPLIT_TOP:    "Split top",
            SPLIT_BOTTOM: "Split bottom",
            SPLIT_RIGHT:  "Split right",
            SPLIT_LEFT:   "Split left",
            CLOSE_VIEW: "Close view",
            SCRIPTING: "Scripting",
            MISC: "Misc",
            DATA: "Data",
            CODE_EDITOR: "Code editor",
            CLOSE: "Close",
            HIERARCHY: "Hierarchy",
            INSPECTOR: "Inspector",
            CONTENT_BROWSER: "Content Browser",
            SHADER_EDITOR: "Shader Editor",
            CONSOLE: "Console"
        }
    }

}